export const transactions = [
  // ===== THIS MONTH (Last 7 days) =====
  {
    type: "expense",
    amount: 250,
    category: "Food & Dining",
    paymentMethod: "cash",
    note: "Lunch",
    transactionDate: new Date("2026-03-19"),
  },
  {
    type: "expense",
    amount: 1200,
    category: "Shopping",
    paymentMethod: "bank",
    note: "Clothes",
    transactionDate: new Date("2026-03-18"),
  },
  {
    type: "income",
    amount: 5000,
    category: "Freelance",
    paymentMethod: "bank",
    note: "Client payment",
    transactionDate: new Date("2026-03-17"),
  },
  {
    type: "expense",
    amount: 300,
    category: "Transport",
    paymentMethod: "cash",
    note: "Auto",
    transactionDate: new Date("2026-03-16"),
  },
  {
    type: "expense",
    amount: 700,
    category: "Groceries",
    paymentMethod: "bank",
    note: "Weekly groceries",
    transactionDate: new Date("2026-03-15"),
  },

  // ===== THIS MONTH (Earlier) =====
  {
    type: "income",
    amount: 20000,
    category: "Salary",
    paymentMethod: "bank",
    note: "Monthly salary",
    transactionDate: new Date("2026-03-05"),
  },
  {
    type: "expense",
    amount: 8000,
    category: "Rent",
    paymentMethod: "bank",
    note: "March rent",
    transactionDate: new Date("2026-03-03"),
  },
  {
    type: "expense",
    amount: 1500,
    category: "Utilities",
    paymentMethod: "bank",
    note: "Electricity bill",
    transactionDate: new Date("2026-03-02"),
  },
  {
    type: "expense",
    amount: 400,
    category: "Entertainment",
    paymentMethod: "cash",
    note: "Movie",
    transactionDate: new Date("2026-03-01"),
  },

  // ===== LAST MONTH =====
  {
    type: "income",
    amount: 20000,
    category: "Salary",
    paymentMethod: "bank",
    note: "Feb salary",
    transactionDate: new Date("2026-02-28"),
  },
  {
    type: "expense",
    amount: 7500,
    category: "Rent",
    paymentMethod: "bank",
    note: "Feb rent",
    transactionDate: new Date("2026-02-27"),
  },
  {
    type: "expense",
    amount: 900,
    category: "Groceries",
    paymentMethod: "cash",
    note: "Groceries",
    transactionDate: new Date("2026-02-25"),
  },
  {
    type: "expense",
    amount: 600,
    category: "Transport",
    paymentMethod: "cash",
    note: "Fuel",
    transactionDate: new Date("2026-02-22"),
  },
  {
    type: "income",
    amount: 3000,
    category: "Gift",
    paymentMethod: "cash",
    note: "Gift received",
    transactionDate: new Date("2026-02-20"),
  },
  {
    type: "expense",
    amount: 1200,
    category: "Health",
    paymentMethod: "bank",
    note: "Medicines",
    transactionDate: new Date("2026-02-18"),
  },
  {
    type: "expense",
    amount: 500,
    category: "Subscriptions",
    paymentMethod: "bank",
    note: "Netflix",
    transactionDate: new Date("2026-02-15"),
  },
  {
    type: "expense",
    amount: 2000,
    category: "Shopping",
    paymentMethod: "bank",
    note: "Shoes",
    transactionDate: new Date("2026-02-10"),
  }
];